# -*- coding: utf-8 -*-
"""actividad4_sys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVAOlhy4XyXPYmB078dYdGicRBazuE_r
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from scipy.signal import butter, cheby1, cheby2, ellip, freqz, lfilter, firwin, firwin2
import warnings
warnings.filterwarnings('ignore')

# Configuración de estilo para gráficos
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

# 1. CREACIÓN DE SEÑALES DE PRUEBA
def crear_ruido_blanco(duracion=1.0, fs=1000, amplitud=1.0):
    """
    Crea una señal de ruido blanco
    """
    t = np.linspace(0, duracion, int(fs * duracion), endpoint=False)
    ruido = amplitud * np.random.randn(len(t))
    return t, ruido

def crear_senal_compuesta(duracion=1.0, fs=1000):
    """
    Crea una señal compuesta de múltiples frecuencias
    """
    t = np.linspace(0, duracion, int(fs * duracion), endpoint=False)

    # Componentes de diferentes frecuencias
    f1, a1 = 10, 1.0    # Frecuencia baja
    f2, a2 = 50, 0.7    # Frecuencia media
    f3, a3 = 150, 0.5   # Frecuencia alta
    f4, a4 = 300, 0.3   # Frecuencia muy alta

    senal = (a1 * np.sin(2 * np.pi * f1 * t) +
             a2 * np.sin(2 * np.pi * f2 * t) +
             a3 * np.sin(2 * np.pi * f3 * t) +
             a4 * np.sin(2 * np.pi * f4 * t))

    # Agregar algo de ruido
    ruido = 0.1 * np.random.randn(len(t))
    senal_con_ruido = senal + ruido

    return t, senal_con_ruido, [f1, f2, f3, f4]

def crear_senal_chirp(duracion=2.0, fs=1000):
    """
    Crea una señal chirp (frecuencia variable en el tiempo)
    """
    t = np.linspace(0, duracion, int(fs * duracion), endpoint=False)
    # Chirp de 10 Hz a 200 Hz
    senal = signal.chirp(t, f0=10, f1=200, t1=duracion, method='linear')
    return t, senal

# 2. DISEÑO DE FILTROS IIR
def disenar_filtro_butterworth(tipo, fc, fs, orden=4):
    """
    Diseña un filtro Butterworth
    tipo: 'lowpass', 'highpass', 'bandpass', 'bandstop'
    """
    nyquist = fs / 2

    if isinstance(fc, (list, tuple)):
        fc_norm = [f / nyquist for f in fc]
    else:
        fc_norm = fc / nyquist

    b, a = butter(orden, fc_norm, btype=tipo, analog=False)
    return b, a

def disenar_filtro_chebyshev1(tipo, fc, fs, orden=4, ripple=0.5):
    """
    Diseña un filtro Chebyshev Tipo I
    """
    nyquist = fs / 2

    if isinstance(fc, (list, tuple)):
        fc_norm = [f / nyquist for f in fc]
    else:
        fc_norm = fc / nyquist

    b, a = cheby1(orden, ripple, fc_norm, btype=tipo, analog=False)
    return b, a

def disenar_filtro_chebyshev2(tipo, fc, fs, orden=4, attenuation=40):
    """
    Diseña un filtro Chebyshev Tipo II
    """
    nyquist = fs / 2

    if isinstance(fc, (list, tuple)):
        fc_norm = [f / nyquist for f in fc]
    else:
        fc_norm = fc / nyquist

    b, a = cheby2(orden, attenuation, fc_norm, btype=tipo, analog=False)
    return b, a

# 3. DISEÑO DE FILTROS FIR
def disenar_filtro_fir_ventana(tipo, fc, fs, numtaps=101, ventana='hamming'):
    """
    Diseña un filtro FIR usando el método de ventana
    """
    nyquist = fs / 2

    if isinstance(fc, (list, tuple)):
        if len(fc) == 2:
            cutoff = [f / nyquist for f in fc]
            if tipo == 'bandpass':
                b = firwin(numtaps, cutoff, pass_zero=False, window=ventana)
            elif tipo == 'bandstop':
                b = firwin(numtaps, cutoff, pass_zero=True, window=ventana)
        else:
            cutoff = fc[0] / nyquist
            b = firwin(numtaps, cutoff, pass_zero=(tipo=='lowpass'), window=ventana)
    else:
        cutoff = fc / nyquist
        b = firwin(numtaps, cutoff, pass_zero=(tipo=='lowpass'), window=ventana)

    a = [1.0]  # FIR solo tiene coeficientes b
    return b, a

# 4. FUNCIONES DE VISUALIZACIÓN
def graficar_senal_original(t, senal, titulo="Señal Original"):
    """
    Grafica la señal en dominio del tiempo y frecuencia
    """
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))

    # Dominio del tiempo
    ax1.plot(t, senal, 'b-', linewidth=1)
    ax1.set_xlabel('Tiempo (s)')
    ax1.set_ylabel('Amplitud')
    ax1.set_title(f'{titulo} - Dominio del Tiempo')
    ax1.grid(True, alpha=0.3)

    # Dominio de la frecuencia
    fs = 1 / (t[1] - t[0])
    n = len(senal)
    freq = np.fft.fftfreq(n, 1/fs)
    fft_vals = np.abs(np.fft.fft(senal))

    # Solo frecuencias positivas hasta Nyquist
    mask = freq >= 0
    freq_pos = freq[mask]
    fft_pos = fft_vals[mask]

    ax2.plot(freq_pos, fft_pos, 'r-', linewidth=1.5)
    ax2.set_xlabel('Frecuencia (Hz)')
    ax2.set_ylabel('Magnitud')
    ax2.set_title(f'{titulo} - Dominio de la Frecuencia')
    ax2.set_xlim([0, fs/2])
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    return fig

def graficar_respuesta_filtro(b, a, fs, titulo="Respuesta del Filtro"):
    """
    Grafica la respuesta en frecuencia del filtro
    """
    w, h = freqz(b, a, worN=8000)
    freq = w * fs / (2 * np.pi)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))

    # Magnitud
    ax1.plot(freq, 20 * np.log10(abs(h)), 'b-', linewidth=2)
    ax1.set_xlabel('Frecuencia (Hz)')
    ax1.set_ylabel('Magnitud (dB)')
    ax1.set_title(f'{titulo} - Respuesta en Magnitud')
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim([0, fs/2])
    ax1.axhline(y=-3, color='r', linestyle='--', alpha=0.5, label='-3 dB')
    ax1.legend()

    # Fase
    ax2.plot(freq, np.angle(h, deg=True), 'g-', linewidth=2)
    ax2.set_xlabel('Frecuencia (Hz)')
    ax2.set_ylabel('Fase (grados)')
    ax2.set_title(f'{titulo} - Respuesta en Fase')
    ax2.grid(True, alpha=0.3)
    ax2.set_xlim([0, fs/2])

    plt.tight_layout()
    return fig

def comparar_senales(t, senal_original, senal_filtrada, fs, titulo="Comparación"):
    """
    Compara señal original y filtrada en tiempo y frecuencia
    """
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Tiempo - Original
    axes[0, 0].plot(t, senal_original, 'b-', linewidth=1, alpha=0.7)
    axes[0, 0].set_xlabel('Tiempo (s)')
    axes[0, 0].set_ylabel('Amplitud')
    axes[0, 0].set_title('Señal Original - Tiempo')
    axes[0, 0].grid(True, alpha=0.3)

    # Tiempo - Filtrada
    axes[0, 1].plot(t, senal_filtrada, 'r-', linewidth=1, alpha=0.7)
    axes[0, 1].set_xlabel('Tiempo (s)')
    axes[0, 1].set_ylabel('Amplitud')
    axes[0, 1].set_title('Señal Filtrada - Tiempo')
    axes[0, 1].grid(True, alpha=0.3)

    # Frecuencia - Original
    n = len(senal_original)
    freq = np.fft.fftfreq(n, 1/fs)
    fft_orig = np.abs(np.fft.fft(senal_original))
    mask = freq >= 0

    axes[1, 0].plot(freq[mask], fft_orig[mask], 'b-', linewidth=1.5)
    axes[1, 0].set_xlabel('Frecuencia (Hz)')
    axes[1, 0].set_ylabel('Magnitud')
    axes[1, 0].set_title('Señal Original - Frecuencia')
    axes[1, 0].set_xlim([0, fs/2])
    axes[1, 0].grid(True, alpha=0.3)

    # Frecuencia - Filtrada
    fft_filt = np.abs(np.fft.fft(senal_filtrada))

    axes[1, 1].plot(freq[mask], fft_filt[mask], 'r-', linewidth=1.5)
    axes[1, 1].set_xlabel('Frecuencia (Hz)')
    axes[1, 1].set_ylabel('Magnitud')
    axes[1, 1].set_title('Señal Filtrada - Frecuencia')
    axes[1, 1].set_xlim([0, fs/2])
    axes[1, 1].grid(True, alpha=0.3)

    plt.suptitle(titulo, fontsize=14, fontweight='bold')
    plt.tight_layout()
    return fig

# 5. FUNCIÓN PRINCIPAL DE DEMOSTRACIÓN
def demostracion_filtros():
    """
    Demostración completa de diseño e implementación de filtros
    """
    print("=" * 60)
    print("DEMOSTRACIÓN DE DISEÑO E IMPLEMENTACIÓN DE FILTROS")
    print("=" * 60)

    # Parámetros
    fs = 1000  # Frecuencia de muestreo
    duracion = 2.0

    # 1. Crear señal de prueba
    print("\n1. Creando señal compuesta de prueba...")
    t, senal_compuesta, frecuencias = crear_senal_compuesta(duracion, fs)
    print(f"   Frecuencias en la señal: {frecuencias} Hz")

    # Graficar señal original
    fig_orig = graficar_senal_original(t, senal_compuesta, "Señal Compuesta Original")
    plt.show()

    # 2. Demostrar diferentes tipos de filtros
    filtros_demo = [
        {
            'nombre': 'Butterworth Pasa Bajos',
            'funcion': disenar_filtro_butterworth,
            'params': {'tipo': 'lowpass', 'fc': 80, 'fs': fs, 'orden': 4}
        },
        {
            'nombre': 'Chebyshev I Pasa Altos',
            'funcion': disenar_filtro_chebyshev1,
            'params': {'tipo': 'highpass', 'fc': 100, 'fs': fs, 'orden': 4, 'ripple': 0.5}
        },
        {
            'nombre': 'FIR con Ventana Hamming Pasa Bajos',
            'funcion': disenar_filtro_fir_ventana,
            'params': {'tipo': 'lowpass', 'fc': 80, 'fs': fs, 'numtaps': 101, 'ventana': 'hamming'}
        },
        {
            'nombre': 'Butterworth Pasa Banda',
            'funcion': disenar_filtro_butterworth,
            'params': {'tipo': 'bandpass', 'fc': [40, 120], 'fs': fs, 'orden': 4}
        }
    ]

    resultados = {}

    for filtro_info in filtros_demo:
        print(f"\n2. Aplicando filtro: {filtro_info['nombre']}...")

        # Diseñar filtro
        b, a = filtro_info['funcion'](**filtro_info['params'])

        # Graficar respuesta del filtro
        fig_resp = graficar_respuesta_filtro(b, a, fs, filtro_info['nombre'])
        plt.show()

        # Aplicar filtro
        senal_filtrada = lfilter(b, a, senal_compuesta)

        # Comparar señales
        fig_comp = comparar_senales(t, senal_compuesta, senal_filtrada, fs,
                                   f"Comparación - {filtro_info['nombre']}")
        plt.show()

        resultados[filtro_info['nombre']] = senal_filtrada

    # 3. Demostración con ruido blanco
    print("\n3. Demostración con ruido blanco...")
    t_ruido, ruido = crear_ruido_blanco(duracion, fs, amplitud=0.5)

    # Agregar una señal senoidal al ruido
    senal_util = 1.0 * np.sin(2 * np.pi * 50 * t_ruido)
    senal_ruidosa = senal_util + ruido

    # Diseñar filtro pasa bajos para eliminar ruido
    b_lp, a_lp = disenar_filtro_butterworth('lowpass', 60, fs, orden=4)
    senal_denoised = lfilter(b_lp, a_lp, senal_ruidosa)

    # Comparar
    fig_denoise = comparar_senales(t_ruido, senal_ruidosa, senal_denoised, fs,
                                   "Eliminación de Ruido - Filtro Pasa Bajos")
    plt.show()

    # 4. Comparación de diferentes órdenes de filtro
    print("\n4. Comparando diferentes órdenes de filtro Butterworth...")
    ordenes = [2, 4, 6, 8]

    fig_ordenes, axes = plt.subplots(len(ordenes), 1, figsize=(12, 10))

    for i, orden in enumerate(ordenes):
        b, a = disenar_filtro_butterworth('lowpass', 80, fs, orden=orden)
        w, h = freqz(b, a, worN=8000)
        freq = w * fs / (2 * np.pi)

        axes[i].plot(freq, 20 * np.log10(abs(h)), linewidth=2)
        axes[i].set_xlabel('Frecuencia (Hz)')
        axes[i].set_ylabel('Magnitud (dB)')
        axes[i].set_title(f'Orden {orden}')
        axes[i].grid(True, alpha=0.3)
        axes[i].set_xlim([0, fs/2])
        axes[i].set_ylim([-80, 5])
        axes[i].axhline(y=-3, color='r', linestyle='--', alpha=0.5)

    plt.suptitle('Comparación de Órdenes de Filtro Butterworth', fontsize=14)
    plt.tight_layout()
    plt.show()

    print("\n" + "=" * 60)
    print("DEMOSTRACIÓN COMPLETADA")
    print("=" * 60)

    return resultados

# 6. EJECUTAR DEMOSTRACIÓN
if __name__ == "__main__":
    resultados = demostracion_filtros()